spring.application.name=sgs-backend

server.port=8080

# Configuración MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/sgs_db

# Si en el futuro se usa MongoDB Atlas:
# spring.data.mongodb.uri=mongodb+srv://<usuario>:<password>@cluster0.mongodb.net/sgs_db

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Clave secreta
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiración del token en milisegundos
jwt.expiration=86400000

# Configuración de correo electrónico
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bgmellado22@gmail.com
spring.mail.password=dsyqjyrzyfjapwiu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true