spring.application.name=sgs-backend

# Servidor y Puerto dinámico para Railway
server.port=${PORT:8080}

# MongoDB (Lee MONGO_URL en Railway o usa localhost en desarrollo local)
spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/sgs_db}

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Seguridad JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000

# Configuración SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:sgs.eltabo.soporte@gmail.com}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true