spring.application.name=sgs-backend

server.port=8080

# Configuración MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/sgs_db

# Si en el futuro se usa MongoDB Atlas:
# spring.data.mongodb.uri=mongodb+srv://<usuario>:<password>@cluster0.mongodb.net/sgs_db

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG